name: bAsset vault unit tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master, withdraw_from_anchor_if_negative_profit, run_unit_tests ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo unit-test --verbose
