[package]
name = "yield_optimizer"
version = "0.1.0"
authors = ["Nexus Labs"]
edition = "2018"
description = "Common yeild-optimizer types"
license = "Apache-2.0"
repository = "https://github.com/nexus/yield-optimizer-contracts"
homepage = "https://nexus.io"
documentation = "https://docs.nexus.io"

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
#TODO: use from crates
cw20 = { git = "https://github.com/CosmWasm/cosmwasm-plus", branch = "main" }
cosmwasm-std = { version = "0.15", features = ["iterator"] }
cosmwasm-storage = { version = "0.15", features = ["iterator"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cosmwasm-bignumber = "2.1.0"

# anchor moneymarket contracts
# moneymarket = { git = "ssh://git@github.com/Anchor-Protocol/money-market-contracts.git", version = "0.1.0", branch = "main" }
